version: '3.9'

services:
  movies:
    build: ../movies_service
    container_name: movies_service
    ports:
      - "5001:5000"

  events:
    build: ../events_service
    container_name: events_service
    ports:
      - "5002:5000"

  weather:
    build: ../weather_service
    container_name: weather_service
    ports:
      - "5003:5000"

  db:
    image: mysql:8.0
    container_name: mysql_db
    ports:
      - "3307:3306"  # Evita conflicto con el MySQL del sistema
    environment:
      MYSQL_ROOT_PASSWORD: PlanifyMe2025!
      MYSQL_DATABASE: planifyme
    volumes:
      - ../docker/db/init.sql:/docker-entrypoint-initdb.d/init.sql
    restart: unless-stopped
    

  app:
    build: ../app
    container_name: main_app
    ports:
      - "5000:5000"
    depends_on:
      - movies
      - events
      - weather
      - db
    environment:
      DB_HOST: db
      DB_USER: admin
      DB_PASSWORD: admin
      DB_NAME: planifyme

volumes:
  mysql_data:
